DROP SEQUENCE ABOUTMESEQ;
DROP TABLE ABOUTME;

CREATE SEQUENCE ABOUTMESEQ;
CREATE TABLE ABOUTME(
	SEQ NUMBER(5) PRIMARY KEY,
	ID VARCHAR2(2000) NOT NULL,   --FK로 NAME,EMAIL,PHONE,ADDRESS,ADDONE,PROFILEIMG 출력
	SITE VARCHAR2(3000),          --BLOG
	CERTIFICATION VARCHAR2(3000),   --자격증
	CONTENT CLOB,               --스킬 및 소개
	CONSTRAINT FK_ABOUTME_ID FOREIGN KEY(ID)
	REFERENCES TESTMEMBER(ID) ON DELETE CASCADE
);