CREATE SEQUENCE CALENDARSEQ;

DROP TABLE CALENDAR;
CREATE TABLE CALENDAR(
	TITLE VARCHAR2(1000) NOT NULL,
	STARTDATE VARCHAR2(1000)
);

delete from calendar;

INSERT INTO CALENDAR
VALUES('제목2','2020-05-14');

select title, startdate,enddate+1 from calendar;