DROP SEQUENCE FEEDSEQ;
CREATE SEQUENCE FEEDSEQ;

DROP TABLE FEED;
CREATE TABLE FEED(
	FEEDNO NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(2000) NOT NULL,
	IMG VARCHAR2(3000),
	VIDEO VARCHAR2(3000),
	CONTENT VARCHAR2(3000),
	WRTDATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_FEED_ID FOREIGN KEY(ID)
	REFERENCES TESTMEMBER(ID) ON DELETE CASCADE
);

delete from feed
where feedno = 3;

INSERT INTO FEED
VALUES(FEEDSEQ.NEXTVAL,'doma',null,null,'너구리다.',sysdate);

SELECT * FROM FEED INNER JOIN TESTMEMBER ON FEED.ID = TESTMEMBER.ID INNER JOIN FEEDCOMMENT
ON FEED.FEEDNO = FEEDCOMMENT.FEEDNO
		ORDER BY FEED.FEEDNO DESC

select * from feed;		
		
-----------------------------------------------------------------

DROP SEQUENCE FEEDCOMMENTSEQ
CREATE SEQUENCE FEEDCOMMENTSEQ;

DROP TABLE FEEDCOMMENT;

CREATE TABLE FEEDCOMMENT(
	RENO NUMBER(10) PRIMARY KEY,
	FEEDNO NUMBER(10) NOT NULL,
	REID VARCHAR2(2000) NOT NULL,
	RECOMMENT VARCHAR2(3000) NOT NULL,
	REDATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_FEEDCOEMMENT_FEEDNO FOREIGN KEY(FEEDNO)
	REFERENCES FEED(FEEDNO) ON DELETE CASCADE,
	CONSTRAINT FK_FEEDCOMMENT_REID FOREIGN KEY(REID)
	REFERENCES TESTMEMBER(ID) ON DELETE CASCADE
);


------------------------------------------------------------------

DROP TABLE LIKETABLE;
CREATE SEQUENCE LIKETABLESEQ;

DROP SEQUENCE LIKETABLESEQ;
CREATE TABLE LIKETABLE(
	LIKENO NUMBER(10) PRIMARY KEY,
	FEEDNO NUMBER(10) NOT NULL,
	LIKEID VARCHAR2(2000) NOT NULL,
	LIKESTATUS NUMBER(2) NOT NULL,       --LIKE상태( 0:like상태(bad버튼나와야됨), 1:bad상태(like버튼 나와야됨))
	CONSTRAINT FK_LIKETABLE_FEEDNO FOREIGN KEY(FEEDNO)
	REFERENCES FEED(FEEDNO) ON DELETE CASCADE,
	CONSTRAINT FK_LIKETABLE_LIKEID FOREIGN KEY(LIKEID)
	REFERENCES TESTMEMBER(ID) ON DELETE CASCADE	
);


select * from liketable order by likeno desc;

MERGE INTO LIKETABLE A 
USING (SELECT LIKENO,FEEDNO,LIKEID,LIKESTATUS FROM LIKETABLE 
	   		   WHERE FEEDNO=16) B
ON (A.LIKENO = B.LIKENO)	   		   
WHEN MATCHED THEN 
	UPDATE SET A.LIKESTATUS = 1
WHEN NOT MATCHED THEN 
	INSERT(LIKENO,FEEDNO,LIKEID,LIKESTATUS)
	VALUES(LIKETABLESEQ.NEXTVAL, 16, 'doma',0);
	
	
INSERT INTO LIKETABLE VALUES(LIKETABLESEQ.NEXTVAL, 16,'doma',0)
						WHERE
						NOT EXISTS (
									SELECT * FROM LIKETABLE
									WHERE FEEDNO=16 AND ID='doma'
									)
	
	

SELECT * FROM LIKETABLE;	
SELECT * FROM FEEDCOMMENT;	

SELECT A.FEEDNO, NVL(CNT,0) LIKECOUNT
FROM FEED A
		,(
		SELECT COUNT(LIKESTATUS) CNT, FEEDNO
		FROM LIKETABLE
		GROUP BY LIKESTATUS,FEEDNO
		HAVING LIKESTATUS = 1) B
WHERE A.FEEDNO = B.FEEDNO(+);		


select * from feedcomment;


select A.feedno, NVL(CNT,0) COMMENTCOUNT
FROM FEED A
		,(
		select count(recomment) CNT,feedno
		from feedcomment
		group by feedno) B
	WHERE A.feedno = B.feedno(+);




INSERT INTO FEEDCOMMENT
VALUES(FEEDCOMMENTSEQ.NEXTVAL,5,'guest','안녕하세요',sysdate);

SELECT * FROM
(SELECT ROWNUM,FEEDCOMMENT.*,TESTMEMBER.* FROM FEEDCOMMENT 
INNER JOIN FEED ON FEEDCOMMENT.FEEDNO = FEED.FEEDNO INNER JOIN TESTMEMBER ON FEEDCOMMENT.REID = TESTMEMBER.ID
WHERE FEEDCOMMENT.FEEDNO=5
ORDER BY FEEDCOMMENT.RENO DESC) A
WHERE ROWNUM = 1;

SELECT * FROM FEEDCOMMENT
		ORDER BY FEEDNO DESC,RENO DESC
		
SELECT * FROM FEED INNER JOIN TESTMEMBER ON FEED.ID = TESTMEMBER.ID
INNER JOIN LIKETABLE ON TESTMEMBER.ID = LIKETABLE.LIKEID
		ORDER BY FEED.FEEDNO DESC		
		
SELECT FEEDNO,LIKEID FROM LIKETABLE	


SELECT * FROM FEED INNER JOIN TESTMEMBER ON FEED.ID = TESTMEMBER.ID
		ORDER BY FEEDNO DESC
		
SELECT * FROM LIKETABLE A INNER JOIN TESTMEMBER B 
ON A.LIKEID = B.ID

select * from liketable order by likeno desc;
